DROP TABLE IF EXISTS Asiakastili CASCADE;
DROP TABLE IF EXISTS Luokan_tuote CASCADE;
DROP TABLE IF EXISTS Tuoteluokka CASCADE;
DROP TABLE IF EXISTS Tarjous CASCADE;
DROP TABLE IF EXISTS Tuote CASCADE;
DROP TABLE IF EXISTS Henkilotiedot CASCADE;
